packages:
  - "apps/*"
  - "tooling/*"
  - "packages/*"

catalog:
  "@hookform/resolvers": ^3.3.4
  "@lucia-auth/adapter-drizzle": ^1.0.2
  "@radix-ui/react-dialog": ^1.0.5
  "@radix-ui/react-dropdown-menu": ^2.0.6
  "@radix-ui/react-label": ^2.1.0
  "@radix-ui/react-separator": ^1.1.0
  "@radix-ui/react-slot": ^1.0.2
  "@radix-ui/react-tooltip": ^1.1.2
  "@t3-oss/env-nextjs": ^0.7.1
  "@tanstack/react-query": ^4.36.1
  "@tanstack/react-table": ^8.11.8
  "@trpc/client": ^10.43.6
  "@trpc/next": ^10.43.6
  "@trpc/react-query": ^10.43.6
  "@trpc/server": ^10.43.6
  "@types/node": ^18.19.14
  autoprefixer: ^10.4.17
  class-variance-authority: ^0.7.0
  clsx: ^2.1.0
  date-fns: ^3.6.0
  dotenv-cli: ^7.3.0
  drizzle-kit: ^0.23.0
  drizzle-orm: ^0.32.0
  geist: ^1.2.1
  lucia: ^3.0.1
  lucide-react: ^0.321.0
  next: ^14.0.4
  next-themes: ^0.2.1
  oslo: ^1.1.3
  pg: ^8.11.3
  postcss: ^8.4.35
  postgres: ^3.4.3
  prettier: ^3.2.5
  react-hook-form: ^7.50.1
  server-only: ^0.0.1
  sonner: ^1.4.0
  superjson: ^2.2.1
  tailwind-merge: ^2.2.1
  tailwindcss: ^3.4.6
  tailwindcss-animate: ^1.0.7
  tsx: ^4.7.0
  typescript: ^5.3.3
  zod: ^3.22.4

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": ^18.2.37
    "@types/react-dom": ^18.2.15
