packages:
  - apps/*
  - tooling/*
  - packages/*

catalog:
  "@hookform/resolvers": ^3.9.0
  "@lucia-auth/adapter-drizzle": ^1.0.7
  "@t3-oss/env-nextjs": ^0.7.3
  "@tanstack/react-query": ^4.36.1
  "@tanstack/react-table": ^8.19.3
  "@trpc/client": ^10.45.2
  "@trpc/next": ^10.45.2
  "@trpc/react-query": ^10.45.2
  "@trpc/server": ^10.45.2
  "@types/node": ^18.19.42
  autoprefixer: ^10.4.19
  class-variance-authority: ^0.7.0
  clsx: ^2.1.1
  date-fns: ^3.6.0
  dotenv-cli: ^7.4.2
  drizzle-kit: ^0.23.0
  drizzle-orm: ^0.32.1
  geist: ^1.3.1
  lucia: ^3.2.0
  lucide-react: ^0.321.0
  next: ^14.2.5
  next-themes: ^0.2.1
  oslo: ^1.2.1
  pg: ^8.12.0
  postcss: ^8.4.40
  postgres: ^3.4.4
  prettier: ^3.3.3
  react-hook-form: ^7.52.1
  server-only: ^0.0.1
  sonner: ^1.5.0
  superjson: ^2.2.1
  tailwind-merge: ^2.4.0
  tailwindcss: ^3.4.7
  tailwindcss-animate: ^1.0.7
  tsx: ^4.16.2
  typescript: 5.3.3
  zod: ^3.23.8

catalogs:
  react18:
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
    react: 18.2.0
    react-dom: 18.2.0
