version: "3.9"

name: finance-nextjs

services:
  # Our local Postgres database instance
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: finance
    volumes:
      - finance-data:/var/lib/postgresql/data
    ports:
      - 5433:5432 # Default postgres port

volumes:
  finance-data:
    driver: local
