name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - name: Sets up PNPM package manager
      uses: pnpm/action-setup@v2

    - name: Setup Node.js LTS with pnpm cache
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"
        cache: "pnpm"

    - shell: bash
      run: pnpm add -g turbo

    - shell: bash
      run: pnpm install

    - name: Setup environment variables for Student
      run: cp .env.example .env
      working-directory: apps/student/

    - name: Setup environment variables for Library
      run: cp .env.example .env
      working-directory: apps/library/

    - name: Setup environment variables for Finance
      run: cp .env.example .env
      working-directory: apps/finance/
