name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - name: Checkout repository into runner
      uses: pnpm/action-setup@v2

    - name: Setup Node.js environment with pnpm cache
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: "pnpm"

    - name: Install Turbo CLI globally
      shell: bash
      run: pnpm add -g turbo

    - name: Install dependencies with pnpm
      shell: bash
      run: pnpm install
