name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github-actions/setup

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Run local databases with Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Setup environment variables
        run: cp .env.example .env
        working-directory: apps/student/

        run: cp .env.example .env
        working-directory: apps/library/

        run: cp .env.example .env
        working-directory: apps/finance/

      - name: Run Playwright tests
        run: cd apps/student/ && pnpm playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
