name: Playwright E2E Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  e2e-tests:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github-actions/setup

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run local databases with Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Setup environment variables for Student
        run: cp .env.example .env
        working-directory: apps/student/

      - name: Setup environment variables for Library
        run: cp .env.example .env
        working-directory: apps/library/

      - name: Setup environment variables for Finance
        run: cp .env.example .env
        working-directory: apps/finance/

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
        run: cd apps/student/ && pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
